export const SITE_CONFIG = {
  homepage: {
    heroTitle: 'India First AI-Powered Job Portal with Real-Time Hiring Near You.',
    heroHighlight: 'Job Portal',
    heroSubtitle: 'Real-Time Hiring Near You.',
    companiesTitle: 'Top companies Hiring',
    premiumTitle: 'Unlock Premium Access',
    premiumSubtitle: 'Get exclusive features and enhanced visibility with our premium membership.',
    resumeTitleGradient: 'ATS-Friendly',
    resumeTitleRest: 'Resume Builder',
    resumeSubtitle: 'Create a professional, Applicant Tracking System (ATS)-friendly CV that increases your chances of getting shortlisted.',
    liveChatTitle: 'Live Chat with Recruiters',
    liveChatSubtitle: 'Connect instantly with recruiters for quicker hiring decisions.',
    postJobTitle: 'Post a Job and Hire faster',
    postJobSubtitle: 'Post jobs and find suitable candidates quickly.',
    exploreNow: 'Explore Now',
    seeAll: 'See All',
    newsTitle: 'Professional media and industry news',
    newsDescription: 'Stay updated with the latest trends, updates, and news shared by industry experts.',
    connectionTitle: 'Nurture your professional relationships with industry experts',
  },
  footer: {
    tagline: 'Nearby Jobs, Live Chat with Recruiters & Networking',
    policies: [
      { label: 'Terms & Conditions', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Location Policy', href: '/location-policy' },
      { label: 'Branding Policy', href: '/branding-policy' },
      { label: 'Fraud Alert Policy', href: '/fraud-alert' },
    ],
    menu: [
      { label: 'About Us', href: '/about' },
      { label: 'Vision & Mission', href: '/vision' },
      { label: 'Service', href: '/service' },
      { label: 'Careers', href: '/careers' },
    ],
    email: 'info@staffbook.in',
    phone: '+91 9009222192',
    social: {
      facebook: 'https://facebook.com/',
      instagram: 'https://instagram.com/',
      linkedin: 'https://linkedin.com/',
      google: 'https://google.com/',
    },
  },
  navbar: {
    navLinks: [
      { label: 'Jobs', href: '/jobs' },
      { label: 'Networking', href: '/networking' },
      { label: 'My Connections', href: '/connections' },
      { label: 'Services', href: '/services' },
    ],
    signUp: 'Sign up',
  },
}; 